# Adding Pandas to our environment

To add Pandas to our environment we must add the package to our uv package manager:

```uv add pandas ```

# Data Series

In the Pandas library, a Data Series (often just called a "series") is one of the fundamental data structures. It is essentially a one-dimensional array-like object that can hold any data type (integers, strings, floats, Python objects, etc.), and it is often used to represent a column in a dataset. Each item in a series has a unique index, which provides a way to access the elements. The index in Pandas is more flexible than in traditional arrays, as it allows for non-numeric labels.  
Here are some key points about Pandas Series:
 
1. **Flexible Indexing**: The index in a Pandas Series does not need to be numeric; it can consist of strings, datetime objects, or even tuples. This flexibility allows for more meaningful and convenient data manipulation and access. 
2. **Data Alignment**: When performing operations between two Series, Pandas automatically aligns data based on the index labels. This feature is very useful for working with data from different sources that may not be in the same order. 
3. **Handling Missing Data**: Pandas Series can easily handle missing or NaN (Not a Number) values, providing a robust way to work with incomplete datasets. 
4. **Vectorized Operations**: Operations on Pandas Series are vectorized, meaning that you can apply functions and operations on the series without needing to loop through its elements explicitly. This leads to concise and efficient code. 
5. **Heterogeneous Data**: A single Series can contain elements of different data types, although it's more common and efficient to have data of the same type. 
6. **Integration with Pandas DataFrame**: A DataFrame in Pandas is essentially a 2-dimensional labeled data structure with columns of potentially different types. You can think of it as a spreadsheet or SQL table. Each column in a DataFrame is a Series.

In [1]:
import pandas as pd

dataSeries = ['F350', 'Jeep', 'Ram', 'Motorcycle']

mySeries = pd.Series(dataSeries)

print(mySeries)

0          F350
1          Jeep
2           Ram
3    Motorcycle
dtype: str

# Data Frame

A DataFrame in Pandas is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns). It is one of the most commonly used Pandas objects, especially for data manipulation and analysis. Think of it as a spreadsheet or SQL table, where each column is a Pandas Series.
 
Here are some key features and characteristics of DataFrames:
 
1. **Labeled Axes**: Both the rows and columns in a DataFrame are labeled. Columns are typically labeled with column names, while rows are labeled with an index. This makes for easy access and manipulation of data based on row and column labels. 
2. **Different Data Types**: Each column in a DataFrame can hold a different data type (e.g., integer, float, string, Python objects, etc.). This is similar to a SQL table or an Excel spreadsheet, where each column can have data of a different type. 
3. **Size Mutable**: DataFrames are size mutable, meaning you can add or delete columns from a DataFrame, and the size of the DataFrame will automatically adjust. 
4. **Flexible Data Manipulation**: Pandas provides a vast array of functions for manipulating, transforming, and aggregating data in DataFrames. Operations such as filtering data based on conditions, grouping data, merging multiple DataFrames, handling missing data, and pivot tables are straightforward. 
5. **Integrated Time Series Functionality**: Pandas has built-in support for handling time series data, making it very convenient to work with time-stamped data. Operations like date range generation, frequency conversion, moving window statistics, and date shifting are seamlessly integrated. 
6. **Efficient Data Storage and Computation**: DataFrames are built on top of the NumPy library, which means they benefit from the fast array-processing capabilities of NumPy. Operations on DataFrames are highly optimized for performance. 
7. **Flexible Indexing and Subsetting**: DataFrames support a range of methods to subset and index data, allowing for complex data selection and manipulation. You can select data by label, by position, by condition (boolean indexing), or a combination of these.

In [3]:
import pandas as pd

myDataFrame = [('F350', 2), ('Jeep', 10), ('Ram', 25), ('Motorcycle', 11)]

mydf = pd.DataFrame(myDataFrame)

mydf

            0   1
0        F350   2
1        Jeep  10
2         Ram  25
3  Motorcycle  11

## Accessing an external data file

In [4]:
import pandas as pd

df = pd.read_csv("http://128.198.162.191/dataFiles/TITANIC/titanic.csv")

In [5]:
# dataframe.info()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [6]:
# dtypes
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [7]:
# Describe the data
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [9]:
df.describe(include='str')

                           Name   Sex  Ticket Cabin Embarked
count                       891   891     891   204      889
unique                      891     2     681   147        3
top     Braund, Mr. Owen Harris  male  347082    G6        S
freq                          1   577       7     4      644

# Learning about new data
.head()

In [17]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [16]:
df[['Name', 'Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

# Working with Data Sets

When loading external data into a DataFrame using Pandas, there are several important factors to consider to ensure the data is loaded correctly and efficiently. Pandas provides functions like read_csv(), read_excel(), read_json(), and others for loading data from various file formats.
Other examples can be found in the Pandas documentation: [https://pandas.pydata.org/docs/user_guide/io.html](https://pandas.pydata.org/docs/user_guide/io.html)

## .loc function

The .loc function in Pandas is a powerful and versatile method used for selecting data from a DataFrame. It allows for indexing and slicing based on labels rather than integer positions. The .loc method provides a way to access a group of rows and columns by labels or a boolean array. It is particularly useful when the indices or column names of a DataFrame are explicitly defined and you want to perform selection operations based on these labels.
 
Here are some key points about the .loc method:

1. **Label-based Selection**: .loc is primarily label based, which means that you use the actual index or column labels to select data. If the index of your DataFrame is a simple range index (0, 1, 2, ...), using .loc with these integers will still work because they are also considered labels in this context.
2. **Slicing**: .loc supports slicing to select a range of data. Unlike normal Python slicing, both the start and the end of the slice are inclusive when using .loc. For example, df.loc[0:5] will include both the rows labeled 0 and 5.
3. **Boolean Indexing**: .loc can also be used with a boolean array to select rows that meet certain conditions. This is particularly useful for filtering data based on some criteria.
4. **Selecting Rows and Columns**: With .loc, you can select both rows and columns in one operation. It accepts a two-dimensional slicing, where the first part specifies the rows and the second part specifies the columns to be selected.
5. **Setting Values**: Beyond just selecting data, .loc can also be used to set values in specific rows and columns based on labels.

In [18]:
# Find passengers over 20 years old. 

df.loc[df['Age']>20]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [19]:
# Search for a person
df.loc[df['Name']=='Braund, Mr. Owen Harris']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [20]:
df.loc[df["Name"].str.contains('Brown', case=False)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
194,195,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.0,0,0,PC 17610,27.7208,B4,C
328,329,1,3,"Goldsmith, Mrs. Frank John (Emily Alice Brown)",female,31.0,1,1,363291,20.5250,NaN,S
345,346,1,2,"Brown, Miss. Amelia ""Mildred""",female,24.0,0,0,248733,13.0000,F33,S
670,671,1,2,"Brown, Mrs. Thomas William Solomon (Elizabeth ...",female,40.0,1,1,29750,39.0000,NaN,S
684,685,0,2,"Brown, Mr. Thomas William Solomon",male,60.0,1,1,29750,39.0000,NaN,S

## .iloc function

The .iloc function in Pandas is a fundamental data selection method used for indexing and selecting data by integer position. Unlike the .loc method, which operates on labels, .iloc allows users to select data based on its numerical position in the DataFrame or Series. This method is particularly useful when the index labels of a DataFrame are not integers, or when you want to select data based on its position regardless of the index labels.
 
Here are some key aspects of the .iloc method:

1. **Integer-based Selection**: .iloc uses integer-based indexing, meaning you select data by its integer location from 0 to the length-1 of the axis. It's similar to how indexing works in Python lists.
2. **Slicing**: Like Python's standard slicing, .iloc supports slicing to select a range of data. The syntax is start:stop:step, where the start index is inclusive and the stop index is exclusive, just like standard Python list slicing.
3. **Select Rows and Columns**: With .iloc, you can select both rows and columns using integers. It accepts a two-dimensional slicing where the first dimension selects rows and the second dimension selects columns.
4. **Negative Indexing**: .iloc supports negative indexing, similar to Python lists, where negative numbers select positions from the end of the DataFrame or Series.
5. **Fancy Indexing**: .iloc supports an array-like index to select specific rows or columns. This means you can pass a list or array of integers to select non-adjacent rows or columns.
6. **Setting Values**: Beyond selection, .iloc can also be used to set values in the DataFrame or Series for specified positions.

In [21]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [23]:
df.iloc[0:3, 2:4]

   Pclass                                               Name
0       3                            Braund, Mr. Owen Harris
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2       3                             Heikkinen, Miss. Laina

In [24]:
# Slice the data to just grab a subset
df_Sub1 = df[['Name', 'Sex', 'Age', 'Survived']]

df_Sub1.head()

                                                Name     Sex   Age  Survived
0                            Braund, Mr. Owen Harris    male  22.0         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0         1
2                             Heikkinen, Miss. Laina  female  26.0         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0         1
4                           Allen, Mr. William Henry    male  35.0         0

# Titanic Data analysis

In [25]:
import pandas as pd

# Get the data
pd.read_csv('http://128.198.162.191/dataFiles/TITANIC/titanic.csv')

df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Titanic Survivors

In [26]:
# Group based on survived
who_Survived = df.groupby('Survived')['Name'].apply(list)

# Print out the results
print("List of Survivors: ", who_Survived[1])
print("List of those not experiencing life: ", who_Survived[0])

List of Survivors:  ['Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'Heikkinen, Miss. Laina', 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 'Nasser, Mrs. Nicholas (Adele Achem)', 'Sandstrom, Miss. Marguerite Rut', 'Bonnell, Miss. Elizabeth', 'Hewlett, Mrs. (Mary D Kingcome) ', 'Williams, Mr. Charles Eugene', 'Masselmani, Mrs. Fatima', 'Beesley, Mr. Lawrence', 'McGowan, Miss. Anna "Annie"', 'Sloper, Mr. William Thompson', 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)', 'O\'Dwyer, Miss. Ellen "Nellie"', 'Spencer, Mrs. William Augustus (Marie Eugenie)', 'Glynn, Miss. Mary Agatha', 'Mamee, Mr. Hanna', 'Nicola-Yarred, Miss. Jamila', 'Laroche, Miss. Simonne Marie Anne Andree', 'Devaney, Miss. Margaret Delia', "O'Driscoll, Miss. Bridget", 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)', 'Woolner, Mr. Hugh', 'Rugg, Miss. Emily', 'West, Miss. Constance Mirium', 'Icard, Miss. Amelie', 'Moubarek, Master. Gerios', 'Nye, Mrs. (Elizabeth Ramell)', 'Andersson, Miss. Erna Alexandra', 'Bing, Mr. Lee', 'Caldwell, Master. Alden Gates', 'Dowdell, Miss. Elizabeth', 'Sheerlinck, Mr. Jan Baptist', 'McDermott, Miss. Brigdet Delia', 'Ilett, Miss. Bertha', 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)', 'Fortune, Miss. Mabel Helen', 'Greenfield, Mr. William Bertram', 'Doling, Mrs. John T (Ada Julia Bone)', 'Salkjelsvik, Miss. Anna Kristine', 'Moss, Mr. Albert Johan', 'Moran, Miss. Bertha', 'Webber, Miss. Susan', 'Nicola-Yarred, Master. Elias', 'Madsen, Mr. Fridtjof Arne', 'Peter, Miss. Anna', 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)', 'Newsom, Miss. Helen Monypeny', 'Nysten, Miss. Anna Sofia', 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)', 'Andersson, Mr. August Edvard ("Wennerstrom")', 'Pears, Mrs. Thomas (Edith Wearne)', 'Gilnagh, Miss. Katherine "Katie"', 'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)', 'Goldsmith, Master. Frank John William "Frankie"', 'Chibnall, Mrs. (Edith Martha Bowerman)', 'Johnson, Miss. Eleanor Ileen', 'Becker, Master. Richard F', 'Kink-Heilmann, Miss. Luise Gretchen', 'O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)', 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")', 'Pinsky, Mrs. (Rosa)', 'Andersen-Jensen, Miss. Carla Christine Nielsine', 'Navratil, Master. Michel M', 'Brown, Mrs. James Joseph (Margaret Tobin)', 'Lurette, Miss. Elise', 'Madigan, Miss. Margaret "Maggie"', 'Cohen, Mr. Gurshon "Gus"', 'Albimona, Mr. Nassef Cassem', 'Carr, Miss. Helen "Ellen"', 'Blank, Mr. Henry', 'Cameron, Miss. Clear Annie', 'Newell, Miss. Madeleine', 'Honkanen, Miss. Eliina', 'Bazzani, Miss. Albina', 'Sunderland, Mr. Victor Francis', 'Hoyt, Mr. Frederick Maxfield', 'Mellors, Mr. William John', 'Harris, Mrs. Henry Birkhardt (Irene Wallach)', 'Asplund, Miss. Lillian Gertrud', 'Collyer, Miss. Marjorie "Lottie"', 'Murphy, Miss. Katherine "Kate"', 'Hamalainen, Mrs. William (Anna)', 'Beckwith, Mr. Richard Leonard', 'Touma, Mrs. Darwis (Hanne Youssef Razi)', 'Thorne, Mrs. Gertrude Maybelle', 'Cherry, Miss. Gladys', 'Ward, Miss. Anna', 'Parrish, Mrs. (Lutie Davis)', 'Asplund, Master. Edvin Rojj Felix', 'Persson, Mr. Ernst Ulrik', 'Graham, Mrs. William Thompson (Edith Junkins)', 'Bissette, Miss. Amelia', 'Tornquist, Mr. William Henry', 'Mellinger, Mrs. (Elizabeth Anne Maidment)', 'Healy, Miss. Hanora "Nora"', 'Andrews, Miss. Kornelia Theodosia', 'Abbott, Mrs. Stanton (Rosa Hunt)', 'Dorking, Mr. Edward Arthur', 'de Mulder, Mr. Theodore', 'Hosono, Mr. Masabumi', 'Connolly, Miss. Kate', 'Barber, Miss. Ellen "Nellie"', 'Bishop, Mrs. Dickinson H (Helen Walton)', 'Saalfeld, Mr. Adolphe', 'Baxter, Mrs. James (Helene DeLaudeniere Chaput)', 'Kelly, Miss. Anna Katherine "Annie Kate"', 'McCoy, Mr. Bernard', 'Keane, Miss. Nora A', 'Allison, Master. Hudson Trevor', 'Fleming, Miss. Margaret', 'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)', 'Francatelli, Miss. Laura Mabel', 'Hays, Miss. Margaret Bechstein', 'Ryerson, Miss. Emily Borie', 'Nilsson, Miss. Helmina Josefina', 'Kantor, Mrs. Sinai (Miriam Sternin)', 'Wick, Miss. Mary Natalie', 'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)', 'Slayter, Miss. Hilda Mary', 'Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)', 'Young, Miss. Marie Grice', 'Ball, Mrs. (Ada E Hall)', 'Goldsmith, Mrs. Frank John (Emily Alice Brown)', 'Hippach, Miss. Jean Gertrude', 'McCoy, Miss. Agnes', 'Frauenthal, Mrs. Henry William (Clara Heinsheimer)', 'Burns, Miss. Elizabeth Margaret', 'Dahl, Mr. Karl Edwart', 'Navratil, Master. Edmond Roger', 'Fortune, Miss. Alice Elizabeth', 'Brown, Miss. Amelia "Mildred"', 'Smith, Miss. Marion Elsie', 'Davison, Mrs. Thomas Henry (Mary E Finck)', 'Coutts, Master. William Loch "William"', 'Bowerman, Miss. Elsie Edith', 'McGovern, Miss. Mary', 'Mockler, Miss. Helen Mary "Ellie"', 'Warren, Mrs. Frank Manley (Anna Sophia Atkinson)', 'Moussa, Mrs. (Mantoura Boulos)', 'Jermyn, Miss. Annie', 'Aubart, Mme. Leontine Pauline', 'Harder, Mr. George Achilles', 'Meyer, Mrs. Edgar Joseph (Leila Saks)', 'Landergren, Miss. Aurora Adelia', 'Bidois, Miss. Rosalie', 'Nakid, Miss. Maria ("Mary")', 'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)', 'Buss, Miss. Kate', 'Lehmann, Miss. Bertha', 'Carter, Mr. William Ernest', 'Jansson, Mr. Carl Olof', 'Newell, Miss. Marjorie', 'Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)', 'Trout, Mrs. William H (Jessie L)', 'Niskanen, Mr. Juha', 'Richards, Master. William Rowe', 'Minahan, Miss. Daisy E', 'Sundman, Mr. Johan Julian', 'Drew, Mrs. James Vivian (Lulu Thorne Christian)', 'Silven, Miss. Lyyli Karoliina', 'Clarke, Mrs. Charles V (Ada Maria Winfield)', 'Phillips, Miss. Kate Florence ("Mrs Kate Louise Phillips Marshall")', 'Pickard, Mr. Berk (Berk Trembisky)', 'Bjornstrom-Steffansson, Mr. Mauritz Hakan', 'Thorneycroft, Mrs. Percival (Florence Kate White)', 'Louch, Mrs. Charles Alexander (Alice Adelaide Slow)', 'Carter, Miss. Lucile Polk', 'Richards, Mrs. Sidney (Emily Hocking)', 'Hart, Mrs. Benjamin (Esther Ada Bloomfield)', 'Reynaldo, Ms. Encarnacion', 'Johannesen-Bratthammer, Mr. Bernt', 'Dodge, Master. Washington', 'Mellinger, Miss. Madeleine Violet', 'Seward, Mr. Frederic Kimber', 'Baclini, Miss. Marie Catherine', 'Peuchen, Major. Arthur Godfrey', 'Goldenberg, Mr. Samuel L', 'Jalsevac, Mr. Ivan', 'Kenyon, Mrs. Frederick R (Marion)', 'Toomey, Miss. Ellen', 'Anderson, Mr. Harry', 'Baclini, Miss. Helene Barbara', 'West, Mrs. Edwy Arthur (Ada Mary Worth)', 'Jerwan, Mrs. Amin S (Marie Marthe Thuillard)', 'Hirvonen, Miss. Hildur E', 'Turkula, Mrs. (Hedwig)', 'Bishop, Mr. Dickinson H', 'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)', 'Coutts, Master. Eden Leslie "Neville"', 'Eustis, Miss. Elizabeth Mussey', 'Maioni, Miss. Roberta', 'Quick, Mrs. Frederick Charles (Jane Richards)', 'Bradley, Mr. George ("George Arthur Brayton")', 'Lang, Mr. Fang', 'Daly, Mr. Eugene Patrick', 'McGough, Mr. James Robert', 'Rothschild, Mrs. Martin (Elizabeth L. Barrett)', 'Lemore, Mrs. (Amelia Milley)', 'Angle, Mrs. William A (Florence "Mary" Agnes Hughes)', 'Perreault, Miss. Anne', 'Hippach, Mrs. Louis Albert (Ida Sophia Fischer)', 'Ridsdale, Miss. Lucy', 'Quick, Miss. Phyllis May', 'Peter, Mrs. Catherine (Catherine Rizk)', 'Hart, Miss. Eva Miriam', 'LeRoy, Miss. Bertha', 'Frolicher, Miss. Hedwig Margaritha', 'Crosby, Miss. Harriet R', 'Beane, Mr. Edward', 'Beane, Mrs. Edward (Ethel Clarke)', 'Padro y Manent, Mr. Julian', 'Davies, Master. John Morgan Jr', 'Thayer, Mr. John Borland Jr', 'Leeni, Mr. Fahim ("Philip Zenni")', 'Ohman, Miss. Velin', 'Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")', 'Taussig, Mrs. Emil (Tillie Mandelbaum)', 'de Messemaeker, Mrs. Guillaume Joseph (Emma)', 'Jonsson, Mr. Carl', 'Harris, Mr. George', 'Appleton, Mrs. Edward Dale (Charlotte Lamson)', 'Flynn, Mr. John Irwin ("Irving")', 'Kelly, Miss. Mary', 'Garside, Miss. Ethel', 'Silvey, Mrs. William Baird (Alice Munger)', 'Jussila, Mr. Eiriik', 'Christy, Miss. Julie Rachel', 'Thayer, Mrs. John Borland (Marian Longstreth Morris)', 'Taussig, Miss. Ruth', 'Frolicher-Stehli, Mr. Maxmillian', 'Stephenson, Mrs. Walter Bertram (Martha Eustis)', 'Leitch, Miss. Jessie Wills', 'Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")', 'Jacobsohn, Mrs. Sidney Samuel (Amy Frances Christy)', 'Homer, Mr. Harry ("Mr E Haven")', 'Daniel, Mr. Robert Williams', 'Laroche, Mrs. Joseph (Juliette Marie Louise Lafargue)', 'Shutes, Miss. Elizabeth W', 'Murphy, Miss. Margaret Jane', 'Herman, Miss. Alice', 'Becker, Miss. Marion Louise', 'Kimball, Mr. Edwin Nelson Jr', 'Nakid, Mr. Sahid', 'Longley, Miss. Gretchen Fiske', 'Barkworth, Mr. Algernon Henry Wilson', 'Stahelin-Maeglin, Dr. Max', 'Davis, Miss. Mary', 'Sagesser, Mlle. Emma', 'Foo, Mr. Choong', 'Baclini, Miss. Eugenie', 'Harper, Mr. Henry Sleeper', 'Simonius-Blumer, Col. Oberst Alfons', 'Stanley, Miss. Amy Zillah Elsie', 'Doling, Miss. Elsie', 'O\'Leary, Miss. Hanora "Norah"', 'Frauenthal, Dr. Henry William', 'Lindqvist, Mr. Eino William', 'Taylor, Mrs. Elmer Zebley (Juliet Cummins Wright)', 'Brown, Mrs. Thomas William Solomon (Elizabeth Catherine Ford)', 'Wilhelms, Mr. Charles', 'Turja, Miss. Anna Sofia', 'Cardeza, Mr. Thomas Drake Martinez', 'Hassab, Mr. Hammad', 'Madill, Miss. Georgette Alexandra', 'Dick, Mr. Albert Adrian', 'Karun, Miss. Manca', 'Lam, Mr. Ali', 'Mullens, Miss. Katherine "Katie"', 'Astor, Mrs. John Jacob (Madeleine Talmadge Force)', 'Silverthorne, Mr. Spencer Victor', 'Kelly, Mrs. Florence "Fannie"', 'Calderhead, Mr. Edward Pennington', 'Cleaver, Miss. Alice', 'Moubarek, Master. Halim Gonios ("William George")', 'Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")', 'Taylor, Mr. Elmer Zebley', 'Endres, Miss. Caroline Louise', 'Troutt, Miss. Edwina Celia "Winnie"', 'Harper, Miss. Annie Jessie "Nina"', 'Chambers, Mr. Norman Campbell', 'Renouf, Mrs. Peter Henry (Lillian Jefferys)', 'Mannion, Miss. Margareth', 'Allen, Miss. Elisabeth Walton', 'Lesurer, Mr. Gustave J', 'Hawksford, Mr. Walter James', 'Ryerson, Miss. Susan Parker "Suzette"', 'Stranden, Mr. Juho', 'Sinkkonen, Miss. Anna', 'Wells, Miss. Joan', 'Moor, Master. Meier', 'Herman, Mrs. Samuel (Jane Laver)', 'Hamalainen, Master. Viljo', 'Rothes, the Countess. of (Lucy Noel Martha Dyer-Edwards)', 'Barah, Mr. Hanna Assi', 'Carter, Mrs. William Ernest (Lucile Polk)', 'Hogeboom, Mrs. John C (Anna Andrews)', 'Hocking, Mrs. Elizabeth (Eliza Needs)', 'Emanuel, Miss. Virginia Ethel', 'Robert, Mrs. Edward Scott (Elisabeth Walton McMillan)', 'Ayoub, Miss. Banoura', 'Dick, Mrs. Albert Adrian (Vera Gillespie)', 'Sjoblom, Miss. Anna Sofia', 'Dean, Master. Bertram Vere', 'Leader, Dr. Alice (Farnham)', 'Osman, Mrs. Mara', 'Collyer, Mrs. Harvey (Charlotte Annie Tate)', 'Carter, Master. William Thornton II', 'Thomas, Master. Assad Alexander', 'Hedman, Mr. Oskar Arvid', 'Chambers, Mrs. Norman Campbell (Bertha Griggs)', 'Hays, Mrs. Charles Melville (Clara Jennings Gregg)', 'Lulic, Mr. Nikola', 'Moor, Mrs. (Beila)', 'Mallet, Master. Andre', 'McCormack, Mr. Thomas Joseph', 'Stone, Mrs. George Nelson (Martha Evelyn)', 'Yasbeck, Mrs. Antoni (Selini Alexander)', 'Richards, Master. George Sibley', 'Compton, Miss. Sara Rebecca', 'Chip, Mr. Chang', 'Marechal, Mr. Pierre', 'Serepeca, Miss. Augusta', 'Goldenberg, Mrs. Samuel L (Edwiga Grabowska)', 'Lines, Miss. Mary Conover', 'Aks, Mrs. Sam (Leah Rosen)', 'Wick, Mrs. George Dennick (Mary Hitchcock)', 'Daly, Mr. Peter Denis ', 'Baclini, Mrs. Solomon (Latifa Qurban)', 'Swift, Mrs. Frederick Joel (Margaret Welles Barron)', 'Bystrom, Mrs. (Karolina)', 'Duran y More, Miss. Asuncion', 'Johnson, Master. Harold Theodor', 'Beckwith, Mrs. Richard Leonard (Sallie Monypeny)', 'Abelson, Mrs. Samuel (Hannah Wizosky)', 'Najib, Miss. Adele Kiamie "Jane"', 'Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)', 'Shelley, Mrs. William (Imanita Parrish Hall)', 'Graham, Miss. Margaret Edith', 'Behr, Mr. Karl Howell']

In [28]:
# Use a loop to present the data more nicely

# Group based on survived
who_Survived = df.groupby('Survived')['Name'].apply(list)

print("Passengers who survived: ")
for name in who_Survived[1]:
    print(name)

print("\n\n")

print("Those not experiencing life: ")
for name in who_Survived[0]:
    print(name)

Passengers who survived:
Cumings, Mrs. John Bradley (Florence Briggs Thayer)
Heikkinen, Miss. Laina
Futrelle, Mrs. Jacques Heath (Lily May Peel)
Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
Nasser, Mrs. Nicholas (Adele Achem)
Sandstrom, Miss. Marguerite Rut
Bonnell, Miss. Elizabeth
Hewlett, Mrs. (Mary D Kingcome)
Williams, Mr. Charles Eugene
Masselmani, Mrs. Fatima
Beesley, Mr. Lawrence
McGowan, Miss. Anna "Annie"
Sloper, Mr. William Thompson
Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)
O'Dwyer, Miss. Ellen "Nellie"
Spencer, Mrs. William Augustus (Marie Eugenie)
Glynn, Miss. Mary Agatha
Mamee, Mr. Hanna
Nicola-Yarred, Miss. Jamila
Laroche, Miss. Simonne Marie Anne Andree
Devaney, Miss. Margaret Delia
O'Driscoll, Miss. Bridget
Harper, Mrs. Henry Sleeper (Myna Haxtun)
Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)
Woolner, Mr. Hugh
Rugg, Miss. Emily
West, Miss. Constance Mirium
Icard, Miss. Amelie
Moubarek, Master. Gerios
Nye, Mrs. (Elizabeth Ramell)
Andersson, Miss. Erna Alexandra
Bing, Mr. Lee
Caldwell, Master. Alden Gates
Dowdell, Miss. Elizabeth
Sheerlinck, Mr. Jan Baptist
McDermott, Miss. Brigdet Delia
Ilett, Miss. Bertha
Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)
Fortune, Miss. Mabel Helen
Greenfield, Mr. William Bertram
Doling, Mrs. John T (Ada Julia Bone)
Salkjelsvik, Miss. Anna Kristine
Moss, Mr. Albert Johan
Moran, Miss. Bertha
Webber, Miss. Susan
Nicola-Yarred, Master. Elias
Madsen, Mr. Fridtjof Arne
Peter, Miss. Anna
Weisz, Mrs. Leopold (Mathilde Francoise Pede)
Newsom, Miss. Helen Monypeny
Nysten, Miss. Anna Sofia
Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)
Andersson, Mr. August Edvard ("Wennerstrom")
Pears, Mrs. Thomas (Edith Wearne)
Gilnagh, Miss. Katherine "Katie"
Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)
Goldsmith, Master. Frank John William "Frankie"
Chibnall, Mrs. (Edith Martha Bowerman)
Johnson, Miss. Eleanor Ileen
Becker, Master. Richard F
Kink-Heilmann, Miss. Luise Gretchen
O'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)
Romaine, Mr. Charles Hallace ("Mr C Rolmane")
Pinsky, Mrs. (Rosa)
Andersen-Jensen, Miss. Carla Christine Nielsine
Navratil, Master. Michel M
Brown, Mrs. James Joseph (Margaret Tobin)
Lurette, Miss. Elise
Madigan, Miss. Margaret "Maggie"
Cohen, Mr. Gurshon "Gus"
Albimona, Mr. Nassef Cassem
Carr, Miss. Helen "Ellen"
Blank, Mr. Henry
Cameron, Miss. Clear Annie
Newell, Miss. Madeleine
Honkanen, Miss. Eliina
Bazzani, Miss. Albina
Sunderland, Mr. Victor Francis
Hoyt, Mr. Frederick Maxfield
Mellors, Mr. William John
Harris, Mrs. Henry Birkhardt (Irene Wallach)
Asplund, Miss. Lillian Gertrud
Collyer, Miss. Marjorie "Lottie"
Murphy, Miss. Katherine "Kate"
Hamalainen, Mrs. William (Anna)
Beckwith, Mr. Richard Leonard
Touma, Mrs. Darwis (Hanne Youssef Razi)
Thorne, Mrs. Gertrude Maybelle
Cherry, Miss. Gladys
Ward, Miss. Anna
Parrish, Mrs. (Lutie Davis)
Asplund, Master. Edvin Rojj Felix
Persson, Mr. Ernst Ulrik
Graham, Mrs. William Thompson (Edith Junkins)
Bissette, Miss. Amelia
Tornquist, Mr. William Henry
Mellinger, Mrs. (Elizabeth Anne Maidment)
Healy, Miss. Hanora "Nora"
Andrews, Miss. Kornelia Theodosia
Abbott, Mrs. Stanton (Rosa Hunt)
Dorking, Mr. Edward Arthur
de Mulder, Mr. Theodore
Hosono, Mr. Masabumi
Connolly, Miss. Kate
Barber, Miss. Ellen "Nellie"
Bishop, Mrs. Dickinson H (Helen Walton)
Saalfeld, Mr. Adolphe
Baxter, Mrs. James (Helene DeLaudeniere Chaput)
Kelly, Miss. Anna Katherine "Annie Kate"
McCoy, Mr. Bernard
Keane, Miss. Nora A
Allison, Master. Hudson Trevor
Fleming, Miss. Margaret
Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)
Francatelli, Miss. Laura Mabel
Hays, Miss. Margaret Bechstein
Ryerson, Miss. Emily Borie
Nilsson, Miss. Helmina Josefina
Kantor, Mrs. Sinai (Miriam Sternin)
Wick, Miss. Mary Natalie
Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)
Slayter, Miss. Hilda Mary
Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)
Young, Miss. Marie Grice
Ball, Mrs. (Ada E Hall)
Goldsmith, Mrs. Frank John (Emily Alice Brown)
Hippach, Miss. Jean Gertrude
McCoy, Miss. Agnes
Frauenthal, Mrs. Henry William (Clara Heinsheimer)
Burns, Miss. Elizabeth Margaret
Dahl, Mr. Karl Edwart
Navratil, Master. Edmond Roger
Fortune, Miss. Alice Elizabeth
Brown, Miss. Amelia "Mildred"
Smith, Miss. Marion Elsie
Davison, Mrs. Thomas Henry (Mary E Finck)
Coutts, Master. William Loch "William"
Bowerman, Miss. Elsie Edith
McGovern, Miss. Mary
Mockler, Miss. Helen Mary "Ellie"
Warren, Mrs. Frank Manley (Anna Sophia Atkinson)
Moussa, Mrs. (Mantoura Boulos)
Jermyn, Miss. Annie
Aubart, Mme. Leontine Pauline
Harder, Mr. George Achilles
Meyer, Mrs. Edgar Joseph (Leila Saks)
Landergren, Miss. Aurora Adelia
Bidois, Miss. Rosalie
Nakid, Miss. Maria ("Mary")
Holverson, Mrs. Alexander Oskar (Mary Aline Towner)
Buss, Miss. Kate
Lehmann, Miss. Bertha
Carter, Mr. William Ernest
Jansson, Mr. Carl Olof
Newell, Miss. Marjorie
Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)
Trout, Mrs. William H (Jessie L)
Niskanen, Mr. Juha
Richards, Master. William Rowe
Minahan, Miss. Daisy E
Sundman, Mr. Johan Julian
Drew, Mrs. James Vivian (Lulu Thorne Christian)
Silven, Miss. Lyyli Karoliina
Clarke, Mrs. Charles V (Ada Maria Winfield)
Phillips, Miss. Kate Florence ("Mrs Kate Louise Phillips Marshall")
Pickard, Mr. Berk (Berk Trembisky)
Bjornstrom-Steffansson, Mr. Mauritz Hakan
Thorneycroft, Mrs. Percival (Florence Kate White)
Louch, Mrs. Charles Alexander (Alice Adelaide Slow)
Carter, Miss. Lucile Polk
Richards, Mrs. Sidney (Emily Hocking)
Hart, Mrs. Benjamin (Esther Ada Bloomfield)
Reynaldo, Ms. Encarnacion
Johannesen-Bratthammer, Mr. Bernt
Dodge, Master. Washington
Mellinger, Miss. Madeleine Violet
Seward, Mr. Frederic Kimber
Baclini, Miss. Marie Catherine
Peuchen, Major. Arthur Godfrey
Goldenberg, Mr. Samuel L
Jalsevac, Mr. Ivan
Kenyon, Mrs. Frederick R (Marion)
Toomey, Miss. Ellen
Anderson, Mr. Harry
Baclini, Miss. Helene Barbara
West, Mrs. Edwy Arthur (Ada Mary Worth)
Jerwan, Mrs. Amin S (Marie Marthe Thuillard)
Hirvonen, Miss. Hildur E
Turkula, Mrs. (Hedwig)
Bishop, Mr. Dickinson H
Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)
Coutts, Master. Eden Leslie "Neville"
Eustis, Miss. Elizabeth Mussey
Maioni, Miss. Roberta
Quick, Mrs. Frederick Charles (Jane Richards)
Bradley, Mr. George ("George Arthur Brayton")
Lang, Mr. Fang
Daly, Mr. Eugene Patrick
McGough, Mr. James Robert
Rothschild, Mrs. Martin (Elizabeth L. Barrett)
Lemore, Mrs. (Amelia Milley)
Angle, Mrs. William A (Florence "Mary" Agnes Hughes)
Perreault, Miss. Anne
Hippach, Mrs. Louis Albert (Ida Sophia Fischer)
Ridsdale, Miss. Lucy
Quick, Miss. Phyllis May
Peter, Mrs. Catherine (Catherine Rizk)
Hart, Miss. Eva Miriam
LeRoy, Miss. Bertha
Frolicher, Miss. Hedwig Margaritha
Crosby, Miss. Harriet R
Beane, Mr. Edward
Beane, Mrs. Edward (Ethel Clarke)
Padro y Manent, Mr. Julian
Davies, Master. John Morgan Jr
Thayer, Mr. John Borland Jr
Leeni, Mr. Fahim ("Philip Zenni")
Ohman, Miss. Velin
Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")
Taussig, Mrs. Emil (Tillie Mandelbaum)
de Messemaeker, Mrs. Guillaume Joseph (Emma)
Jonsson, Mr. Carl
Harris, Mr. George
Appleton, Mrs. Edward Dale (Charlotte Lamson)
Flynn, Mr. John Irwin ("Irving")
Kelly, Miss. Mary
Garside, Miss. Ethel
Silvey, Mrs. William Baird (Alice Munger)
Jussila, Mr. Eiriik
Christy, Miss. Julie Rachel
Thayer, Mrs. John Borland (Marian Longstreth Morris)
Taussig, Miss. Ruth
Frolicher-Stehli, Mr. Maxmillian
Stephenson, Mrs. Walter Bertram (Martha Eustis)
Leitch, Miss. Jessie Wills
Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")
Jacobsohn, Mrs. Sidney Samuel (Amy Frances Christy)
Homer, Mr. Harry ("Mr E Haven")
Daniel, Mr. Robert Williams
Laroche, Mrs. Joseph (Juliette Marie Louise Lafargue)
Shutes, Miss. Elizabeth W
Murphy, Miss. Margaret Jane
Herman, Miss. Alice
Becker, Miss. Marion Louise
Kimball, Mr. Edwin Nelson Jr
Nakid, Mr. Sahid
Longley, Miss. Gretchen Fiske
Barkworth, Mr. Algernon Henry Wilson
Stahelin-Maeglin, Dr. Max
Davis, Miss. Mary
Sagesser, Mlle. Emma
Foo, Mr. Choong
Baclini, Miss. Eugenie
Harper, Mr. Henry Sleeper
Simonius-Blumer, Col. Oberst Alfons
Stanley, Miss. Amy Zillah Elsie
Doling, Miss. Elsie
O'Leary, Miss. Hanora "Norah"
Frauenthal, Dr. Henry William
Lindqvist, Mr. Eino William
Taylor, Mrs. Elmer Zebley (Juliet Cummins Wright)
Brown, Mrs. Thomas William Solomon (Elizabeth Catherine Ford)
Wilhelms, Mr. Charles
Turja, Miss. Anna Sofia
Cardeza, Mr. Thomas Drake Martinez
Hassab, Mr. Hammad
Madill, Miss. Georgette Alexandra
Dick, Mr. Albert Adrian
Karun, Miss. Manca
Lam, Mr. Ali
Mullens, Miss. Katherine "Katie"
Astor, Mrs. John Jacob (Madeleine Talmadge Force)
Silverthorne, Mr. Spencer Victor
Kelly, Mrs. Florence "Fannie"
Calderhead, Mr. Edward Pennington
Cleaver, Miss. Alice
Moubarek, Master. Halim Gonios ("William George")
Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")
Taylor, Mr. Elmer Zebley
Endres, Miss. Caroline Louise
Troutt, Miss. Edwina Celia "Winnie"
Harper, Miss. Annie Jessie "Nina"
Chambers, Mr. Norman Campbell
Renouf, Mrs. Peter Henry (Lillian Jefferys)
Mannion, Miss. Margareth
Allen, Miss. Elisabeth Walton
Lesurer, Mr. Gustave J
Hawksford, Mr. Walter James
Ryerson, Miss. Susan Parker "Suzette"
Stranden, Mr. Juho
Sinkkonen, Miss. Anna
Wells, Miss. Joan
Moor, Master. Meier
Herman, Mrs. Samuel (Jane Laver)
Hamalainen, Master. Viljo
Rothes, the Countess. of (Lucy Noel Martha Dyer-Edwards)
Barah, Mr. Hanna Assi
Carter, Mrs. William Ernest (Lucile Polk)
Hogeboom, Mrs. John C (Anna Andrews)
Hocking, Mrs. Elizabeth (Eliza Needs)
Emanuel, Miss. Virginia Ethel
Robert, Mrs. Edward Scott (Elisabeth Walton McMillan)
Ayoub, Miss. Banoura
Dick, Mrs. Albert Adrian (Vera Gillespie)
Sjoblom, Miss. Anna Sofia
Dean, Master. Bertram Vere
Leader, Dr. Alice (Farnham)
Osman, Mrs. Mara
Collyer, Mrs. Harvey (Charlotte Annie Tate)
Carter, Master. William Thornton II
Thomas, Master. Assad Alexander
Hedman, Mr. Oskar Arvid
Chambers, Mrs. Norman Campbell (Bertha Griggs)
Hays, Mrs. Charles Melville (Clara Jennings Gregg)
Lulic, Mr. Nikola
Moor, Mrs. (Beila)
Mallet, Master. Andre
McCormack, Mr. Thomas Joseph
Stone, Mrs. George Nelson (Martha Evelyn)
Yasbeck, Mrs. Antoni (Selini Alexander)
Richards, Master. George Sibley
Compton, Miss. Sara Rebecca
Chip, Mr. Chang
Marechal, Mr. Pierre
Serepeca, Miss. Augusta
Goldenberg, Mrs. Samuel L (Edwiga Grabowska)
Lines, Miss. Mary Conover
Aks, Mrs. Sam (Leah Rosen)
Wick, Mrs. George Dennick (Mary Hitchcock)
Daly, Mr. Peter Denis
Baclini, Mrs. Solomon (Latifa Qurban)
Swift, Mrs. Frederick Joel (Margaret Welles Barron)
Bystrom, Mrs. (Karolina)
Duran y More, Miss. Asuncion
Johnson, Master. Harold Theodor
Beckwith, Mrs. Richard Leonard (Sallie Monypeny)
Abelson, Mrs. Samuel (Hannah Wizosky)
Najib, Miss. Adele Kiamie "Jane"
Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
Shelley, Mrs. William (Imanita Parrish Hall)
Graham, Miss. Margaret Edith
Behr, Mr. Karl Howell



Those not experiencing life:
Braund, Mr. Owen Harris
Allen, Mr. William Henry
Moran, Mr. James
McCarthy, Mr. Timothy J
Palsson, Master. Gosta Leonard
Saundercock, Mr. William Henry
Andersson, Mr. Anders Johan
Vestrom, Miss. Hulda Amanda Adolfina
Rice, Master. Eugene
Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)
Fynney, Mr. Joseph J
Palsson, Miss. Torborg Danira
Emir, Mr. Farred Chehab
Fortune, Mr. Charles Alexander
Todoroff, Mr. Lalio
Uruchurtu, Don. Manuel E
Wheadon, Mr. Edward H
Meyer, Mr. Edgar Joseph
Holverson, Mr. Alexander Oskar
Cann, Mr. Ernest Charles
Vander Planke, Miss. Augusta Maria
Ahlin, Mrs. Johan (Johanna Persdotter Larsson)
Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)
Kraeff, Mr. Theodor
Rogers, Mr. William John
Lennon, Mr. Denis
Samaan, Mr. Youssef
Arnold-Franchi, Mrs. Josef (Josefine Franchi)
Panula, Master. Juha Niilo
Nosworthy, Mr. Richard Cater
Ostby, Mr. Engelhart Cornelius
Novel, Mr. Mansouer
Goodwin, Master. William Frederick
Sirayanian, Mr. Orsen
Harris, Mr. Henry Birkhardt
Skoog, Master. Harald
Stewart, Mr. Albert A
Crease, Mr. Ernest James
Kink, Mr. Vincenz
Jenkin, Mr. Stephen Curnow
Goodwin, Miss. Lillian Amy
Hood, Mr. Ambrose Jr
Chronopoulos, Mr. Apostolos
Moen, Mr. Sigurd Hansen
Staneff, Mr. Ivan
Moutal, Mr. Rahamin Haim
Waelens, Mr. Achille
Carrau, Mr. Francisco M
Ford, Mr. William Neal
Slocovski, Mr. Selman Francis
Celotti, Mr. Francesco
Christmann, Mr. Emil
Andreasson, Mr. Paul Edvin
Chaffee, Mr. Herbert Fuller
Dean, Mr. Bertram Frank
Coxon, Mr. Daniel
Shorney, Mr. Charles Joseph
Goldschmidt, Mr. George B
Kantor, Mr. Sinai
Petranec, Miss. Matilda
Petroff, Mr. Pastcho ("Pentcho")
White, Mr. Richard Frasar
Johansson, Mr. Gustaf Joel
Gustafsson, Mr. Anders Vilhelm
Mionoff, Mr. Stoytcho
Rekic, Mr. Tido
Porter, Mr. Walter Chamberlain
Zabour, Miss. Hileni
Barton, Mr. David John
Jussila, Miss. Katriina
Attalah, Miss. Malake
Pekoniemi, Mr. Edvard
Connors, Mr. Patrick
Turpin, Mr. William John Robert
Baxter, Mr. Quigg Edmond
Andersson, Miss. Ellis Anna Maria
Hickman, Mr. Stanley George
Moore, Mr. Leonard Charles
Nasser, Mr. Nicholas
White, Mr. Percival Wayland
McMahon, Mr. Martin
Ekstrom, Mr. Johan
Drazenoic, Mr. Jozef
Coelho, Mr. Domingos Fernandeo
Robins, Mrs. Alexander A (Grace Charity Laury)
Sobey, Mr. Samuel James Hayden
Richard, Mr. Emile
Futrelle, Mr. Jacques Heath
Osen, Mr. Olaf Elon
Giglio, Mr. Victor
Boulos, Mrs. Joseph (Sultana)
Burke, Mr. Jeremiah
Andrew, Mr. Edgardo Samuel
Nicholls, Mr. Joseph Charles
Ford, Miss. Robina Maggie "Ruby"
Navratil, Mr. Michel ("Louis M Hoffman")
Byles, Rev. Thomas Roussel Davids
Bateman, Rev. Robert James
Meo, Mr. Alfonzo
van Billiard, Mr. Austin Blyler
Olsen, Mr. Ole Martin
Williams, Mr. Charles Duane
Corn, Mr. Harry
Smiljanic, Mr. Mile
Sage, Master. Thomas Henry
Cribb, Mr. John Hatfield
Bengtsson, Mr. John Viktor
Calic, Mr. Jovo
Panula, Master. Eino Viljami
Skoog, Mrs. William (Anna Bernhardina Karlsson)
Baumann, Mr. John D
Ling, Mr. Lee
Van der hoef, Mr. Wyckoff
Rice, Master. Arthur
Sivola, Mr. Antti Wilhelm
Smith, Mr. James Clinch
Klasen, Mr. Klas Albin
Lefebre, Master. Henry Forbes
Isham, Miss. Ann Elizabeth
Hale, Mr. Reginald
Leonard, Mr. Lionel
Sage, Miss. Constance Gladys
Pernot, Mr. Rene
Asplund, Master. Clarence Gustaf Hugo
Rood, Mr. Hugh Roscoe
Bourke, Mr. John
Turcin, Mr. Stjepan
Carbines, Mr. William
Mernagh, Mr. Robert
Olsen, Mr. Karl Siegwart Andreas
Yrois, Miss. Henriette ("Mrs Harbeck")
Vande Walle, Mr. Nestor Cyriel
Sage, Mr. Frederick
Johanson, Mr. Jakob Alfred
Youseff, Mr. Gerious
Strom, Miss. Telma Matilda
Backstrom, Mr. Karl Alfred
Ali, Mr. Ahmed
Perkin, Mr. John Henry
Givard, Mr. Hans Kristensen
Kiernan, Mr. Philip
Jacobsohn, Mr. Sidney Samuel
Harris, Mr. Walter
Bracken, Mr. James H
Green, Mr. George Henry
Nenkoff, Mr. Christo
Berglund, Mr. Karl Ivar Sven
Lovell, Mr. John Hall ("Henry")
Fahlstrom, Mr. Arne Jonas
Lefebre, Miss. Mathilde
Larsson, Mr. Bengt Edvin
Sjostedt, Mr. Ernst Adolf
Leyson, Mr. Robert William Norman
Harknett, Miss. Alice Phoebe
Hold, Mr. Stephen
Pengelly, Mr. Frederick William
Hunt, Mr. George Henry
Zabour, Miss. Thamine
Coleridge, Mr. Reginald Charles
Maenpaa, Mr. Matti Alexanteri
Attalah, Mr. Sleiman
Minahan, Dr. William Edward
Lindahl, Miss. Agda Thorilda Viktoria
Carter, Rev. Ernest Courtenay
Reed, Mr. James George
Strom, Mrs. Wilhelm (Elna Matilda Persson)
Stead, Mr. William Thomas
Lobb, Mr. William Arthur
Rosblom, Mrs. Viktor (Helena Wilhelmina)
Smith, Mr. Thomas
Taussig, Mr. Emil
Harrison, Mr. William
Henry, Miss. Delia
Reeves, Mr. David
Panula, Mr. Ernesti Arvid
Cairns, Mr. Alexander
Natsch, Mr. Charles H
Lindblom, Miss. Augusta Charlotta
Parkes, Mr. Francis "Frank"
Rice, Master. Eric
Duane, Mr. Frank
Olsson, Mr. Nils Johan Goransson
de Pelsmaeker, Mr. Alfons
Smith, Mr. Richard William
Stankovic, Mr. Ivan
Naidenoff, Mr. Penko
Levy, Mr. Rene Jacques
Haas, Miss. Aloisia
Mineff, Mr. Ivan
Lewy, Mr. Ervin G
Hanna, Mr. Mansour
Allison, Miss. Helen Loraine
Johnson, Mr. William Cahoone Jr
Williams, Mr. Howard Hugh "Harry"
Abelson, Mr. Samuel
Lahtinen, Mrs. William (Anna Sylfven)
Hendekovic, Mr. Ignjac
Hart, Mr. Benjamin
Moraweck, Dr. Ernest
Dennis, Mr. Samuel
Danoff, Mr. Yoto
Sage, Mr. George John Jr
Nysveen, Mr. Johan Hansen
Partner, Mr. Austen
Graham, Mr. George Edward
Vander Planke, Mr. Leo Edmondus
Denkoff, Mr. Mitto
Pears, Mr. Thomas Clinton
Blackwell, Mr. Stephen Weart
Collander, Mr. Erik Gustaf
Sedgwick, Mr. Charles Frederick Waddington
Fox, Mr. Stanley Hubert
Dimic, Mr. Jovan
Odahl, Mr. Nils Martin
Williams-Lambert, Mr. Fletcher Fellows
Elias, Mr. Tannous
Arnold-Franchi, Mr. Josef
Yousif, Mr. Wazli
Vanden Steen, Mr. Leo Peter
Funk, Miss. Annie Clemmer
Skoog, Mr. Wilhelm
del Carlo, Mr. Sebastiano
Barbara, Mrs. (Catherine David)
Asim, Mr. Adola
O'Brien, Mr. Thomas
Adahl, Mr. Mauritz Nils Martin
Wiklund, Mr. Jakob Alfred
Beavan, Mr. William Thomas
Ringhini, Mr. Sante
Palsson, Miss. Stina Viola
Widener, Mr. Harry Elkins
Betros, Mr. Tannous
Gustafsson, Mr. Karl Gideon
Tikkanen, Mr. Juho
Plotcharsky, Mr. Vasil
Davies, Mr. Charles Henry
Goodwin, Master. Sidney Leonard
Sadlier, Mr. Matthew
Gustafsson, Mr. Johan Birger
Johansson, Mr. Erik
Olsson, Miss. Elina
McKane, Mr. Peter David
Pain, Dr. Alfred
Adams, Mr. John
Jussila, Miss. Mari Aina
Hakkarainen, Mr. Pekka Pietari
Oreskovic, Miss. Marija
Gale, Mr. Shadrach
Widegren, Mr. Carl/Charles Peter
Birkeland, Mr. Hans Martin Monsen
Lefebre, Miss. Ida
Sdycoff, Mr. Todor
Hart, Mr. Henry
Cunningham, Mr. Alfred Fleming
Meek, Mrs. Thomas (Annie Louise Rowley)
Matthews, Mr. William John
Van Impe, Miss. Catharina
Gheorgheff, Mr. Stanio
Charters, Mr. David
Zimmerman, Mr. Leo
Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)
Rosblom, Mr. Viktor Richard
Wiseman, Mr. Phillippe
Flynn, Mr. James
Kallio, Mr. Nikolai Erland
Silvey, Mr. William Baird
Ford, Miss. Doolina Margaret "Daisy"
Fortune, Mr. Mark
Kvillner, Mr. Johan Henrik Johannesson
Hampe, Mr. Leon
Petterson, Mr. Johan Emil
West, Mr. Edwy Arthur
Hagland, Mr. Ingvald Olai Olsen
Foreman, Mr. Benjamin Laventall
Peduzzi, Mr. Joseph
Millet, Mr. Francis Davis
O'Connor, Mr. Maurice
Morley, Mr. William
Gee, Mr. Arthur H
Milling, Mr. Jacob Christian
Maisner, Mr. Simon
Goncalves, Mr. Manuel Estanslas
Campbell, Mr. William
Smart, Mr. John Montgomery
Scanlan, Mr. James
Keefe, Mr. Arthur
Cacic, Mr. Luka
Strandberg, Miss. Ida Sofia
Clifford, Mr. George Quincy
Renouf, Mr. Peter Henry
Braund, Mr. Lewis Richard
Karlsson, Mr. Nils August
Goodwin, Master. Harold Victor
Frost, Mr. Anthony Wood "Archie"
Rouse, Mr. Richard Henry
Lefebre, Miss. Jeannie
Kent, Mr. Edward Austin
Somerton, Mr. Francis William
Hagland, Mr. Konrad Mathias Reiersen
Windelov, Mr. Einar
Molson, Mr. Harry Markland
Artagaveytia, Mr. Ramon
Stanley, Mr. Edward Roland
Yousseff, Mr. Gerious
Shellard, Mr. Frederick William
Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
Svensson, Mr. Olof
Calic, Mr. Petar
Canavan, Miss. Mary
O'Sullivan, Miss. Bridget Mary
Laitinen, Miss. Kristina Sofia
Penasco y Castellana, Mr. Victor de Satode
Olsen, Mr. Henry Margido
Webber, Mr. James
Coleff, Mr. Satio
Walker, Mr. William Anderson
Ryan, Mr. Patrick
Pavlovic, Mr. Stefo
Vovk, Mr. Janko
Lahoud, Mr. Sarkis
Kassem, Mr. Fared
Farrell, Mr. James
Farthing, Mr. John
Salonen, Mr. Johan Werner
Hocking, Mr. Richard George
Toufik, Mr. Nakli
Elias, Mr. Joseph Jr
Cacic, Miss. Marija
Butt, Major. Archibald Willingham
Risien, Mr. Samuel Beard
Andersson, Miss. Ingeborg Constanzia
Andersson, Miss. Sigrid Elisabeth
Douglas, Mr. Walter Donald
Nicholson, Mr. Arthur Ernest
Goldsmith, Mr. Frank John
Sharp, Mr. Percival James R
O'Brien, Mr. Timothy
Wright, Mr. George
Robbins, Mr. Victor
Morrow, Mr. Thomas Rowan
Sivic, Mr. Husein
Norman, Mr. Robert Douglas
Simmons, Mr. John
Meanwell, Miss. (Marion Ogden)
Davies, Mr. Alfred J
Stoytcheff, Mr. Ilia
Palsson, Mrs. Nils (Alma Cornelia Berglund)
Doharr, Mr. Tannous
Rush, Mr. Alfred George John
Patchett, Mr. George
Caram, Mrs. Joseph (Maria Elias)
Downton, Mr. William James
Ross, Mr. John Hugo
Paulner, Mr. Uscher

## How many Men vs Women survived?

In [30]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [29]:
survivedBySex = df.groupby(['Survived', 'Sex']).size()

print(survivedBySex)

Survived  Sex
0         female     81
          male      468
1         female    233
          male      109
dtype: int64

## Odds of survival by sex

In [32]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [34]:
# First filter the survivors and others by sex.
maleSurvived =df[(df['Sex'] == 'male') & (df['Survived'] ==1)].shape[0]
maleDied = df[(df['Sex'] == 'male') & (df['Survived'] ==0)].shape[0]

femaleSurvived =df[(df['Sex'] == 'female') & (df['Survived'] ==1)].shape[0]
femaleDied = df[(df['Sex'] == 'female') & (df['Survived'] ==0)].shape[0]

#Calculate the odds of survival
maleOdds = maleSurvived / maleDied
femaleOdds = femaleSurvived / femaleDied

print(f'Odds of survival for Men: {maleOdds:.2f}')
print(f'Odds of survival for Women: {femaleOdds:.2f}')

Odds of survival for Men: 0.23
Odds of survival for Women: 2.88