In [18]:
import pandas as pd

df = pd.read_csv("http://128.198.162.191/dataFiles/TITANIC/titanic.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Dealing with missing data

In [19]:
df['Survived'].isna()

df['Age'].isna()

df['Age'].isna().sum()

# Show empty values for each label (column) in the dataframe

df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [20]:
# Locate the specific blank records
df.loc[df['Age'].isna(), :] # The colon signifies "show me everything".

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [21]:
# Identify those records with values in the Age column.

# Use the "NOT" (~) character to return the reverse of the search.
df_noNull = df.loc[~df['Age'].isna()]

df_noNull['Age'].isna()

0      False
1      False
2      False
3      False
4      False
       ...
885    False
886    False
887    False
889    False
890    False
Name: Age, Length: 714, dtype: bool

In [22]:
df_noNull.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [23]:
# Cast data to a different type

df_noNull['Age'].astype('int')

0      22
1      38
2      26
3      35
4      35
       ..
885    39
886    27
887    19
889    26
890    32
Name: Age, Length: 714, dtype: int64

# Data Analysis for Titanic

## Number of passengers per class

In [24]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [25]:
# Ratio of 'Fare' and 'Survived'

# Create a new column in our dataframe called 'SurvivalOdds'
df['SurvivalOdds'] = df['Survived']/df['Fare']

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,SurvivalOdds
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.000000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0.014029
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0.126183
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0.018832
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.000000

In [26]:
# Compare number of survivors versus not.

survival_counts = df['Survived'].value_counts()

survival_counts

Survived
0    549
1    342
Name: count, dtype: int64

In [27]:
# Replace values with more readable values
df['Survived'] = df['Survived'].replace({0:'No', 1:'Yes'})

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,SurvivalOdds
0,1,No,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.000000
1,2,Yes,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0.014029
2,3,Yes,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0.126183
3,4,Yes,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0.018832
4,5,No,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,No,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0.000000
887,888,Yes,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0.033333
888,889,No,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0.000000
889,890,Yes,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0.033333
890,891,No,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0.000000

In [28]:
# Create a ratio of surviving passengers.

survival_prop = df['Suvived'].mean()

survival_prop

KeyError: 'Suvived'

In [30]:
# Revert back to numeric before calculating the mean.
df['Survived'] = df['Survived'].replace({'No':0, 'Yes':1})

survival_prop = df['Survived'].mean()

survival_prop

np.float64(0.3838383838383838)

In [31]:
df.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,SurvivalOdds
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S,0.0

## Look at the number of passengers per class

In [34]:
class_counts = df['Pclass'].value_counts().sort_index()

class_counts

Pclass
1    216
2    184
3    491
Name: count, dtype: int64

In [35]:
# Calculate the average paid per class
df.groupby('Pclass')['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [36]:
# Average age of passengers who survived and didn't
df.groupby('Survived')['Age'].mean()

Survived
0    30.626179
1    28.343690
Name: Age, dtype: float64

## Odds of surviving by passenger class

In [38]:
# First Group by class and survival
class_survival_counts = df.groupby('Pclass')['Survived'].value_counts().unstack()

# Calculate the ods of survival for each class
odds_of_survival = class_survival_counts[1] / class_survival_counts[0]

# Print the results
odds_of_survival

Pclass
1    1.700000
2    0.896907
3    0.319892
dtype: float64

# IMDB analysis

In [42]:
import pandas as pd

dfTitles = pd.read_csv('http://128.198.162.191/dataFiles/IMDB/titleBasics.tsv', sep='\t', low_memory=False)
dfRatings = pd.read_csv('http://128.198.162.191/dataFiles/IMDB/ratings.tsv', sep='\t', low_memory=False)
dfNames = pd.read_csv('http://128.198.162.191/dataFiles/IMDB/nameBasics.tsv', sep='\t', low_memory=False)
dfCrew = pd.read_csv('http://128.198.162.191/dataFiles/IMDB/crew.tsv', sep='\t', low_memory=False)

In [44]:
dfTitles.head(2)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"

In [45]:
dfRatings.head(2)

      tconst  averageRating  numVotes
0  tt0000001            5.7      1957
1  tt0000002            5.8       263

In [46]:
dfNames.head(2)

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"soundtrack,actor,miscellaneous","tt0045537,tt0050419,tt0053137,tt0072308"
1,nm0000002,Lauren Bacall,1924,2014,"actress,soundtrack","tt0117057,tt0071877,tt0038355,tt0037382"

In [47]:
dfCrew.head(2)

      tconst  directors writers
0  tt0000001  nm0005690      \N
1  tt0000002  nm0721526      \N

# What was the name and year of the movie with the highest rating and highest number of votes.

In [48]:
# Join the dataframes we need
mvRating = pd.merge(dfTitles, dfRatings, on='tconst')

mvRating

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short",5.7,1957
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short",5.8,263
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance",6.5,1790
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short",5.6,179
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short",6.2,2593
...,...,...,...,...,...,...,...,...,...,...,...
1284586,tt9916730,movie,6 Gunn,6 Gunn,0,2017,\N,116,\N,8.3,10
1284587,tt9916766,tvEpisode,Episode #10.15,Episode #10.15,0,2019,\N,43,"Family,Game-Show,Reality-TV",7.0,21
1284588,tt9916778,tvEpisode,Escape,Escape,0,2019,\N,\N,"Crime,Drama,Mystery",7.2,36
1284589,tt9916840,tvEpisode,Horrid Henry's Comic Caper,Horrid Henry's Comic Caper,0,2014,\N,11,"Adventure,Animation,Comedy",8.8,6
1284590,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,\N,10,"Adventure,Animation,Comedy",8.2,6

In [49]:
# Query to reduce the data to only movies
ratingSort = (mvRating.query('titleType == "movie"'))

ratingSort

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes
8,tt0000009,movie,Miss Jerry,Miss Jerry,0,1894,\N,45,Romance,5.3,204
144,tt0000147,movie,The Corbett-Fitzsimmons Fight,The Corbett-Fitzsimmons Fight,0,1897,\N,100,"Documentary,News,Sport",5.2,466
326,tt0000502,movie,Bohemios,Bohemios,0,1905,\N,100,\N,4.1,15
358,tt0000574,movie,The Story of the Kelly Gang,The Story of the Kelly Gang,0,1906,\N,70,"Action,Adventure,Biography",6.0,815
365,tt0000591,movie,The Prodigal Son,L'enfant prodigue,0,1907,\N,90,Drama,4.4,20
...,...,...,...,...,...,...,...,...,...,...,...
1284561,tt9916270,movie,Il talento del calabrone,Il talento del calabrone,0,2020,\N,84,Thriller,5.8,1400
1284565,tt9916362,movie,Coven,Akelarre,0,2020,\N,92,"Drama,History",6.4,5200
1284569,tt9916428,movie,The Secret of China,Hong xing zhao yao Zhong guo,0,2019,\N,\N,"Adventure,History,War",3.8,14
1284574,tt9916538,movie,Kuambil Lagi Hatiku,Kuambil Lagi Hatiku,0,2019,\N,123,Drama,8.3,6
1284586,tt9916730,movie,6 Gunn,6 Gunn,0,2017,\N,116,\N,8.3,10

In [50]:
# Sort our dataframe to finish answering our question
ratingSort.sort_values(by='averageRating', ascending=False)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes
835736,tt21236128,movie,We Are Art Through the Eyes of Annalaura,We Are Art Through the Eyes of Annalaura,0,2022,\N,69,Documentary,10.0,10
913222,tt26696489,movie,Yooper Creoles: Finnish Music in Michigan's Co...,Yooper Creoles: Finnish Music in Michigan's Co...,0,2019,\N,57,Documentary,10.0,5
618684,tt13458442,movie,Vegan on a Jet Plane: Bali,Vegan on a Jet Plane: Bali,0,2021,\N,50,Documentary,10.0,13
721691,tt15881774,movie,Time and motion 2,Time and motion 2,0,2021,\N,90,Documentary,10.0,20
532659,tt11654554,movie,The Fragile King,The Fragile King,0,2022,\N,90,Drama,10.0,6
...,...,...,...,...,...,...,...,...,...,...,...
738002,tt1645915,movie,Stand Up Face the Fear,Stand Up Face the Fear,0,2008,\N,65,"Comedy,Documentary",1.0,36
1239842,tt8654080,movie,Overdose of Gore: Crime born Crime,Overdose of Gore: Crime born Crime,0,2015,\N,46,Horror,1.0,31
1240206,tt8665056,movie,Guns Along The Bravo,Guns Along The Bravo,0,2001,\N,85,Western,1.0,6
950925,tt3262718,movie,"Bai bai, marâno","Bai bai, marâno",0,2013,\N,114,Drama,1.0,274
1179670,tt7221896,movie,Cumali Ceber,Cumali Ceber: Allah Seni Alsin,0,2017,\N,100,Comedy,1.0,39142

In [54]:
# Sort by multiple columns to accurately answer the question
ratingSort.sort_values(by=['averageRating', 'numVotes'], ascending = False)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes
832308,tt21101694,movie,In Pursuit of Flavor,In Pursuit of Flavor,0,2022,\N,60,Documentary,10.0,40
494195,tt10925174,movie,Petersburg's tram,Petersburg's tram,0,2007,\N,74,"Documentary,History",10.0,26
481016,tt10663998,movie,Widow of the Revolution: The Anna Larina Story,Widow of the Revolution: The Anna Larina Story,0,2000,\N,\N,Documentary,10.0,25
584035,tt12745710,movie,Publish or Perish,Publish or Perish,0,2023,\N,100,Comedy,10.0,25
838642,tt21345048,movie,Tahanan (Home),Tahanan (Home),0,2022,\N,62,"Drama,Romance",10.0,22
...,...,...,...,...,...,...,...,...,...,...,...
1184978,tt7332864,movie,Der Schuldschein des Pandola,Der Schuldschein des Pandola,0,1918,\N,\N,"Adventure,Crime",1.0,8
779202,tt18302390,movie,The Little Chinese Mermaid,The Little Chinese Mermaid,0,2019,\N,\N,Romance,1.0,7
1240206,tt8665056,movie,Guns Along The Bravo,Guns Along The Bravo,0,2001,\N,85,Western,1.0,6
1254058,tt9027346,movie,Apocalypse Again: Acceptance of Inheritance,Apokalypsi akoma: Apodohi klironomias,0,2018,\N,84,Documentary,1.0,6
839344,tt21372706,movie,Nuh'un Gemisi Cudi'de 2,Nuh'un Gemisi Cudi'de 2,0,2022,\N,\N,Comedy,1.0,5

In [53]:
# Sort by multiple columns to accurately answer the question
ratingSort.sort_values(by=['numVotes', 'averageRating'], ascending = False)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes
82382,tt0111161,movie,The Shawshank Redemption,The Shawshank Redemption,0,1994,\N,142,Drama,9.3,2707952
249538,tt0468569,movie,The Dark Knight,The Dark Knight,0,2008,\N,152,"Action,Crime,Drama",9.0,2681200
632482,tt1375666,movie,Inception,Inception,0,2010,\N,148,"Action,Adventure,Sci-Fi",8.8,2379176
98830,tt0137523,movie,Fight Club,Fight Club,0,1999,\N,139,Drama,8.8,2152147
81289,tt0109830,movie,Forrest Gump,Forrest Gump,0,1994,\N,142,"Drama,Romance",8.8,2104001
...,...,...,...,...,...,...,...,...,...,...,...
814683,tt20183562,movie,Torment,Torment,0,2022,\N,73,"Horror,Thriller",1.8,5
1188101,tt7407470,movie,The Road Back,Wu ye jing hun lu,0,2017,\N,75,"Drama,Horror,Mystery",1.8,5
499372,tt11012390,movie,Laagi Tohse Lagan,Laagi Tohse Lagan,0,2015,\N,155,Drama,1.6,5
642289,tt13977250,movie,Livrés chez vous sans contact,Livrés chez vous sans contact,0,2021,\N,77,\N,1.4,5
839344,tt21372706,movie,Nuh'un Gemisi Cudi'de 2,Nuh'un Gemisi Cudi'de 2,0,2022,\N,\N,Comedy,1.0,5

### Question:
What was the name and year of the movie with the highest rating and highest number of votes.

In [57]:
# Let's format the output for the end user.
semi1 = (ratingSort.sort_values(by=['averageRating', 'numVotes'], ascending=False))

# Create a dataframe with only the asked for columns.
semi2 = semi1[['primaryTitle', 'startYear', 'averageRating', 'numVotes']]

# Select a subset of the rows for the report
final = (semi2.head(5))

print(final)

                                          primaryTitle startYear  \
832308                            In Pursuit of Flavor      2022
494195                               Petersburg's tram      2007
481016  Widow of the Revolution: The Anna Larina Story      2000
584035                               Publish or Perish      2023
838642                                  Tahanan (Home)      2022

        averageRating  numVotes
832308           10.0        40
494195           10.0        26
481016           10.0        25
584035           10.0        25
838642           10.0        22

In [ ]:
# Export the results to a file
final.to_csv('files/top5Movies.csv', index=False)